apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- helm-repository.yaml
- helm-release.yaml
- image-catalog.yaml
- prometheusrule.yaml
- plugin-barman-cloud.yaml
- postgres-sql-exporter-cluster-role.yaml
- barman-cloud-server-secret.yaml
- barman-cloud-client-secret.yaml
