apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: anonymizer
  namespace: anonymizer
spec:
  type: "oci"
  interval: 168h
  url: oci://cr.yandex/crp2cvbrp76d7dmfegco/helm-charts
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: anonymizer-staging
#   namespace: anonymizer
# spec:
#   chart:
#     spec:
#       chart: anonymizer-app
#       version: '2.0.0'
#       sourceRef:
#         kind: HelmRepository
#         name: anonymizer
#   dependsOn:
#     - name: anonymizer-init-staging
#   interval: 168h
#   values:
#     name: anonymizer-staging
#     environmentName: staging
#     runtimeEnvironment: staging
#     packageVersion: 1.0.198 # {"$imagepolicy": "flux-system:anonymizer:tag"}
#     jobCorrelationId: "tobedeleted"
#     product: anonymizer
#     services:
#       name: anonymizer-staging-services
#       imageName: anonymizer_services
#       replicas: "1"
#       resources:
#         limits:
#           memory: "512Mi"
#         requests:
#           cpu: "500m"
#           memory: "256Mi"
#       ingressRoute:
#         enabled: false # traefik dependency
#         enableIpFiltering: false
#         host: anonymizer-staging.mindbox.ru
#       reliable: false
#       envFrom:
#         - secretRef:
#             name: manual-secrets
#     lrt:
#       imageName: anonymizer_worker
#       roles:
#         - replicas: "1"
#           resources:
#             limits:
#               memory: "1024Mi"
#             requests:
#               cpu: "800m"
#               memory: "256Mi"
#           envFrom:
#             - secretRef:
#                 name: manual-secrets
#     containerRegistry: ru
#     zoneIndex: yandex
#     commonEnv:
#       - name: PostgreSqlDatabase__username
#         valueFrom:
#           secretKeyRef:
#             name: db-anonymizer-staging-anonymizer-user-password
#             key: username
#       - name: PostgreSqlDatabase__password
#         valueFrom:
#           secretKeyRef:
#             name: db-anonymizer-staging-anonymizer-user-password
#             key: password
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: anonymizer-init-staging
#   namespace: anonymizer
# spec:
#   chart:
#     spec:
#       chart: anonymizer-app-init
#       version: '1.0.2'
#       sourceRef:
#         kind: HelmRepository
#         name: anonymizer
#   interval: 168h
#   values:
#     name: anonymizer-staging
#     environmentName: staging
#     runtimeEnvironment: staging
#     packageVersion: 1.0.198 # {"$imagepolicy": "flux-system:anonymizer:tag"}
#     jobCorrelationId: "tobedeleted"
#     checkRollback:
#       enabled: false
#     initialization:
#       enabled: false
#     sqlmigrator:
#       imageName: anonymizer_migrator
#     containerRegistry: ru
#     migrations:
#       enabled: true
#       env:
#       - name: PostgreSqlDatabase__username
#         valueFrom:
#           secretKeyRef:
#             name: db-anonymizer-staging-anonymizer-user-password
#             key: username
#       - name: PostgreSqlDatabase__password
#         valueFrom:
#           secretKeyRef:
#             name: db-anonymizer-staging-anonymizer-user-password
#             key: password
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: anonymizer-staging-pg-cluster
  namespace: anonymizer
spec:
  chart:
    spec:
      chart: anonymizer-postgres
      version: '1.0.0'
      sourceRef:
        kind: HelmRepository
        name: anonymizer
  interval: 168h
  values:
    clusterName: ru-staging-yc-kube-common1
    environment: staging
    feature: anonymizer
    product: cdp
    postgres:
      databaseName: anonymizer
      storage:
        storageClass: "yc-network-ssd"
        size: 186Gi
      resources:
        requests:
          cpu: "200m"
          memory: "1Gi"
        limits:
          memory: "2Gi"
      managedRoles:
        enabled: true
        roles:
        - name: anonymizer-user
          ensure: present
          login: true
          inRoles:
          - db_owner
