apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-operator-crds
  namespace: prometheus
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '^55.0.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: prometheus
  values:
    # Отключаем все компоненты, оставляем только CRD
    grafana:
      enabled: false
    
    prometheus:
      enabled: false
    
    alertmanager:
      enabled: false
    
    nodeExporter:
      enabled: false
    
    kubeStateMetrics:
      enabled: false
    
    # Включаем только CRD
    prometheusOperator:
      enabled: true
      # Минимальные ресурсы для CRD
      resources:
        limits:
          memory: 128Mi
          cpu: 50m
        requests:
          memory: 64Mi
          cpu: 25m
